# Generated by Django 5.0.14 on 2025-06-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('orientador', models.CharField(max_length=255)),
                ('coorientador', models.CharField(max_length=255)),
                ('resumo', models.TextField()),
                ('abstract', models.TextField()),
                ('palavras_chave', models.CharField(help_text='Separe as palavras por vírgula', max_length=255)),
                ('data_defesa', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arquivo', models.FileField(upload_to='monografias/')),
            ],
        ),
    ]
